### ISSUE TITLE
Translation of periods for Vaccination datasets

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/msf_appproject#40]

**Comment by HelderCastrillon** [comment]
It was implemented the translation of periods for Vaccination datasets

**Comment by HelderCastrillon** [comment]
I didn't find the project in Toggl,  the development time was 25 minutes.

**Comment by ifoche** [comment]
Hi @HelderCastrillon I've just modified toggl to give you access, can you see the project now? could you please charge that time there? thanks!

**Comment by HelderCastrillon** [comment]
thanks @ifoche  , I could already put the time.
