### ISSUE TITLE
Health sites: Add a comment about the length​  of the prefix

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/msf_appproject#44]
It should be 3 characters

**Comment by josemp10** [comment]
@HelderCastrillon , the alarm only is shown when the user introduces more than 3 characters. The prefix should be exactly 3 characters lenght. Maybe we would need to add a label displaying that information

**Comment by HelderCastrillon** [comment]
The reason I desinged it of this way is because it doesn't have space to one label of alert. To development what you want was neccessary to move the prefix field to final of the fields.

I hope this will be correct and it doesn't affect  the implementation.
